# Iris Classification

In [1]:
 pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
  Using cached tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Using cached tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [17]:
# Step 1 : Import Libraries

import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [3]:
# Step 2 :Load Dataset

iris = load_iris()

x = iris.data
y = iris.target

# Create DataFrame 
df = pd.DataFrame(x,columns = iris.feature_names)

# Add target column

df['Target'] = y

# Display first Five rows
df.head()



,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [4]:
# Step 3 : Preprocessing

# Check null values 
print(df.isnull().sum())

# Check Duplicate values
print(df.duplicated().sum())

# Dataset Shape 
print(df.shape)
# Dataset Info
print(df.info())


sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Target               0
dtype: int64
1
(150, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB
None


In [5]:
# Step 4 : Separate input and output

x = df.drop('Target',axis = 1)
y = df['Target']

In [6]:
# Step 5 : Label Encoding

le = LabelEncoder()

y = le.fit_transform(y)

# One-hot-encoding

y_encoded = to_categorical(y)
print(y_encoded[:5])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [7]:
# Step 6 : Normalize features
scaler = StandardScaler()

X_scaled = scaler.fit_transform(x)
print(X_scaled[:5])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


In [8]:
# Step 7 :Train-test split

X_train,X_test, y_train, y_test = train_test_split(
    X_scaled,
    y_encoded,
    test_size = 0.2,
    random_state = 42
)

print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)


In [9]:
# Step 8: Build the Model

model = Sequential()
# Hidden Layer 1 
model.add(Dense(10,input_shape=(4,),activation = 'relu'))

# Hidden Layer 2 
model.add(Dense(8,activation='relu'))

# Output Layer 
model.add(Dense(3,activation = 'softmax'))

C:\Users\SINAN\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
# Step 9 : Compile The model 

model.compile(
    optimizer = 'adam',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

In [11]:
# Step 10 : Train the model

history = model.fit(
    X_train,
    y_train,
    epochs = 50,
    batch_size =8,
    validation_split = 0.2
)


Epoch 1/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - accuracy: 0.2500 - loss: 1.1879 - val_accuracy: 0.2083 - val_loss: 1.1884
Epoch 2/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3125 - loss: 1.1506 - val_accuracy: 0.3333 - val_loss: 1.1493
Epoch 3/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4271 - loss: 1.1175 - val_accuracy: 0.4167 - val_loss: 1.1106
Epoch 4/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5000 - loss: 1.0815 - val_accuracy: 0.5417 - val_loss: 1.0685
Epoch 5/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5521 - loss: 1.0438 - val_accuracy: 0.6667 - val_loss: 1.0288
Epoch 6/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6250 - loss: 1.0075 - val_accuracy: 0.7083 - val_loss: 0.9882
Epoch 7/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6771 - loss: 0.9690 - val_accuracy: 0.7917 - val_loss: 0.9465
Epoch 8/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6875 - loss: 0.9256 - val_accuracy: 0.7917 - v

In [12]:
# Step : 11 Evaluate the model

loss,accuracy = model.evaluate(X_test, y_test)

print("Loss:",loss)
print("Accuracy",accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 280ms/step - accuracy: 1.0000 - loss: 0.1547
Loss: 0.15469810366630554
Accuracy 1.0


In [13]:
# Step 12: Prediction

y_pred = model.predict(X_test)

# Convert predicted values
y_pred_classes = np.argmax(y_pred, axis = 1)

# Convert avtual values
y_test_classes = np.argmax(y_test, axis = 1)

print("Predicted Values:")
print(y_pred_classes[:10])

print("Actual Values :")
print(y_test_classes[:10])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
Predicted Values:
[1 0 2 1 1 0 1 2 1 1]
Actual Values :
[1 0 2 1 1 0 1 2 1 1]


In [14]:
# Step 13 : Accuracy Score

from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test_classes,y_pred_classes)
print("Accuracy Score:",acc)

Accuracy Score: 1.0


In [15]:
# Step 14 : Classification Report

from sklearn.metrics import classification_report

print(classification_report(y_test_classes,y_pred_classes))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [16]:
import joblib
from tensorflow.keras.models import load_model

# Save model
model.save("iris_ann_model.h5")

# Save scaler
joblib.dump(scaler, "iris_scaler.pkl")

print("Model and scaler saved successfully!")


loaded_model = load_model("iris_ann_model.h5")
loaded_scaler = joblib.load("iris_scaler.pkl")


unseen_flower = np.array([[6.1, 2.8, 4.7, 1.2]])

# Scale the input
unseen_flower_scaled = loaded_scaler.transform(unseen_flower)

# Predict
prediction = loaded_model.predict(unseen_flower_scaled)

predicted_class = np.argmax(prediction, axis=1)[0]

# Convert class index to species name
species_names = ['setosa', 'versicolor', 'virginica']
predicted_species = species_names[predicted_class]

print("\nUnseen Flower Sample:")
print(unseen_flower)

print("\nPrediction Probabilities:")
print(prediction)


print("\nPredicted Species:", predicted_species)

Model and scaler saved successfully!


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Unseen Flower Sample:
[[6.1 2.8 4.7 1.2]]

Prediction Probabilities:
[[0.0145916  0.77381855 0.21158989]]

Predicted Species: versicolor
